### ISSUE TITLE
More than one same sensors?

### ISSUE THREAD

**Issue by marius-fh34** [Johboh/HomeAssistantEntities#1]
Your "HomeAssistantEntities" is a wonderful help for me - and works fine!! :-)
But now I'm trying to display TWO -temperature- sensors, but only one appears at a time in HA.
Is it possible? (I can only do it with 2 _different_ entities, e.g. temperature and brightness)
My attempts were something like this:

`HaEntityTemperature _ha_entity_temperature_in(ha_bridge, "TEMP In");`
`HaEntityTemperature _ha_entity_temperature_out(ha_bridge, "TEMP Out");  // not ok?`
(... in loop: ..)
`_ha_entity_temperature_in.publishTemperature_in(MyTemperatureIn);`
`_ha_entity_temperature_in.publishTemperature_out(MyTemperatureOut);  // not ok?`

Best regards,
marius

**Comment by Johboh** [comment]
Hi!
Yes this is possible. Just set the third parameter, child ID, to a unique ID/path in the constructor of HaEntityTemperature: https://github.com/Johboh/HomeAssistantEntities/blob/main/src/entities/HaEntityTemperature.h#L55
```
HaEntityTemperature _ha_entity_temperature_in(ha_bridge, "TEMP in",  "temp_in" );
HaEntityTemperature _ha_entity_temperature_out(ha_bridge, "TEMP Out", "temp_out");
```

**Comment by marius-fh34** [comment]
Uhh, that wasn't so difficult ;-) Thank you very much!
(Sorry, I'm not a "pro" - but I'm working hard on it..) :-D

**Comment by Johboh** [comment]
No problem! Let me know if there is anything else.
I will update the sensors example to include this, as it's a common setup.

//Johan
